{% set name = "tango-idl" %}
{% set version = "6.0a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/tango-idl/-/archive/6.0-alpha2/tango-idl-6.0-alpha2.tar.gz
  sha256: 9f2050e88fafdb08b798fc393dc38f95ced86c998dcbbcb81e66f87da42b643d

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/tango.idl                        # [unix]
    - test -f $PREFIX/lib/pkgconfig/tangoidl.pc                # [unix]
    - if not exist %LIBRARY_INC%\tango.idl exit 1 .            # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\tangoidl.pc exit 1  # [win]

about:
  home: http://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: This is the Tango CORBA IDL file
  description: |
    TANGO is an object oriented distributed control system. It allows
    communication between TANGO device processes running on the same
    computer or distributed over the network. These processes can
    provide services to the control system all over the network, such as
    hardware control or data processing.
  doc_url: https://tango-controls.readthedocs.io/
  dev_url: https://gitlab.com/tango-controls/tango-idl

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
